return {
  {
    'codethread/qmk.nvim',
    ft = 'dts',
    ---@type qmk.UserConfig
    opts = {
      name = 'corneo',
      variant = 'zmk',
      auto_format_pattern = '*.keymap',
      comment_preview = {
        keymap_overrides = {
          ['&trans'] = '',
          ['&sys_reset'] = '🔄',
          ['&bootloader'] = '💾',
          ['&studio_unlock'] = '🔓',
          ['&bt '] = '🛜',
          BT_NXT = '🔼',
          BT_PRV = '🔽',
          BT_CLR = '❌',
          BT_SEL = '',
          C_MUTE = '🔇',
          C_VOL_DN = '🔉',
          C_VOL_UP = '🔊',
          C_BRI_UP = '🔆',
          C_BRI_DN = '🔅',
          ['&ext_power EP_TOG'] = '🔌',
          AMPS = '&',
          STAR = '*',
          LPAR = '(',
          RPAR = ')',
          MEH = 'MEH',
          HYPER = 'HYPER',
          ['COPY'] = '📄',
          ['PASTE'] = '📋',
          ['CUT'] = '✂️',
          ['LG(Q)'] = '⌘Q',
          ['RG(W)'] = '⌘W',
          ['LC(W)'] = '⌃W',
          ['LC(TAB)'] = '⌃⇥',
          SPACE = '␣',
          KP_MULTIPLY = '*',
          -- use MENU as compose key
          K_CMENU = '🌍',
          K_MENU = '🌍',
          COMPOSE = '🌍',
          LEFT = '←',
          RIGHT = '→',
          UP = '↑',
          DOWN = '↓',
          KP_PLUS = '+',
          DQT = '"',
          PG_UP = '⇞',
          PG_DN = '⇟',
          HOME = '⇱',
          END = '⇲',
          -- mouse stuff
          MB1 = '🖱️L',
          MB2 = '🖱️R',
          MB3 = '🖱️M',
          MB4 = '🖱️B4',
          MB5 = '🖱️F5',
          MOVE_X = '🖱️X',
          MOVE_Y = '🖱Y',
          MOUSE_MOVE_GEAR1_VAL = '1',
          MOUSE_MOVE_GEAR2_VAL = '2',
          MOUSE_MOVE_GEAR3_VAL = '3',
          MOUSE_MOVE_GEAR4_VAL = '4',
          MOUSE_SCROLL_GEAR1_VAL = '1',
          MOUSE_SCROLL_GEAR2_VAL = '2',
          MOUSE_SCROLL_GEAR3_VAL = '3',
          MOUSE_SCROLL_GEAR4_VAL = '4',
        },
      },
      layout = {
        'x x x x x x _ _ x x x x x x',
        'x x x x x x _ _ x x x x x x',
        'x x x x x x _ _ x x x x x x',
        '_ _ _ x x x _ _ x x x _ _ _',
      },
    },
  },
}
